# Mysql in Docker : mysql 구동 시 docker process 실행
spring:
  jpa:
    database-platform: mysql
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jenkinsbatch?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: password
  batch:
    initialize-schema: never
    job:
      names: ${job.name:NONE}
      enabled: true
  main:
    web-application-type: none
  profiles:
    active: dev

logging:
  level:
    root: INFO
    org:
      springframework:
        batch: DEBUG
        boot:
          autoconfigure: ERROR
